obj-$(CONFIG_TOUCHSCREEN_EPHTouch) += eswin.o
eswin-objs						   := eswin_eph861x.o eswin_eph861x_bootloader.o eswin_eph861x_comms.o eswin_eph861x_eswin.o eswin_eph861x_i2c.o eswin_eph861x_spi.o  eswin_eph861x_tlv_command.o eswin_eph861x_tlv_report.o 
